# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="Consulting company web site https://www.fini.net/"
REPO_LICENSE=""
REPO_TOPICS="consultancy,hugo-site,justfile,website"

# URLs section
REPO_GIT_SSH="git@github.com:fini-net/www-fini-net.git"
REPO_WEB_URL="https://github.com/fini-net/www-fini-net"

# Derived values
REPO_ORG_NAME="fini-net"
REPO_REPO_NAME="www-fini-net"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="false"
FLAG_CLAUDE_REVIEW="false"
FLAG_COPILOT_REVIEW="false"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "consultancy"
    "hugo-site"
    "justfile"
    "website"
)
