baseURL = '/'

# maybe, see https://discourse.gohugo.io/t/viewing-a-site-without-a-server/35825
#uglyURLs = true
#relativeURLs = true
languageCode = 'en-us'
title = "FINI.net Consultants"

theme = ["github.com/adityatelange/hugo-PaperMod"]

[[module.imports]]
path = "github.com/adityatelange/hugo-PaperMod"

# ignore txt files (they came from TWiki conversion and should go away eventually)
[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
  excludeFiles = ['*.txt']

[params]
#body_classes = "avenir bg-near-white"
schema.publisherType = "Person"
ShowReadingTime = true
ShowShareButtons = true
# it would be nice to add bluesky to this list
ShareButtons = ["linkedin","reddit","facebook","whatsapp","telegram","ycombinator"]
ShowBreadCrumbs = true
ShowWordCount = true
#ShowCodeCopyButtons = true
UseHugoToc = true
comments = false
author = "Christopher Hicks"
keywords = ["Flamingo Internet Navigators", "Consulting", "FINI"]

[params.assets]
# favicon = ""
theme_color = "#a903fc"

[params.profileMode]
enabled = true
title = "FINI.net"
subtitle = "technology consulting services"
imageUrl = "/servers-2010-08-03_18.37.59.jpg"
imageTitle = "Servers that chicks was working on in 2010."
imageWidth = 716
imageHeight = 724

[[params.profileMode.buttons]]
name = "Our Services"
url = "/FiniServices"

[[params.profileMode.buttons]]
name = "New Clients"
url = "https://docs.google.com/forms/d/e/1FAIpQLSdwOgvaqUax1uGf89m79s7hFK90JK81jqZ8wAYhQGcg9thHmA/viewform?usp=header"

[[params.profileMode.buttons]]
name = "Blog"
url = "/EdgeReports"

[[params.profileMode.buttons]]
name = "Feedback"
url = "https://docs.google.com/forms/d/e/1FAIpQLSe0kmh8-z6qh6Ajw3SFjyDTaxJS7jJ1h5IXg_QlJFYTBgOIxg/viewform?usp=header"

[[params.profileMode.buttons]]
name = "Service Status"
url = "https://status.fini.net"

[[menu.main]]
identifier = "services"
name = "Services"
url = "/FiniServices"
weight = 10

[[menu.main]]
identifier = "feedback"
name = "Feedback"
url = "https://docs.google.com/forms/d/e/1FAIpQLSe0kmh8-z6qh6Ajw3SFjyDTaxJS7jJ1h5IXg_QlJFYTBgOIxg/viewform?usp=header"
weight = 15

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/EdgeReports"
weight = 20

[[menu.main]]
identifier = "terms"
name = "Terms & Conditions"
url = "/TermsAndConditions"
weight = 30

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive"
weight = 80

[[menu.main]]
identifier = "status"
name = "Status"
url = "https://status.fini.net"
weight = 90

[[params.socialIcons]]
name = "github"
url = "https://github.com/fini-net"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/company/flamingo-internet-navigators/"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/@ChristopherHicksFINI"

[[params.socialIcons]]
name = "serverfault"
url = "https://serverfault.com/users/205542/chicks"
